name: Echo Run Number

on: 
  push:
    branches:
      - master

jobs:
  echo-run-number:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the Run Number
        run: echo "This is run number ${{ github.run_number }}"
  pull-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: |
          docker pull nginx:555534235fg
      - name: Always pull the other image
        # This will always pull image, even on failure. However the exit code of the failure + failed repo will show too!
        # USE THIS TO CLEAN UP AFTER JOBS!
        if: always()
        run: |
          docker pull alpine
