name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    # if we write any steps here - they will run inside of this container
    steps:
      - name: log node.js version
        run: |
          cat /etc/os-release
          node -v
      # BUT we can write a step that uses it's own container
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        # we can also overwrite the ENTRYPOINT of this docker container with use the with key
        with:
          entrypoint: '/bin/echo'
          args: "Hello World"
      - name: Log node.js version
        uses: docker://node:12.14.1-alpine3.10
        # we can also overwrite the ENTRYPOINT of this docker container with use the with key
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        # we can also overwrite the ENTRYPOINT of this docker container with use the with key
        with:
          entrypoint: ./script/sh
          args: "Some String"
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo:4
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: |
          curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{"username": "hello","address": "dwded"}'
      - name: Get Users
        run: |
          curl http://localhost:3001/api/users
