name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    # because we are specifiying a container - this will go inside the container and any steps will be run inside that container
    steps:
      - name: Log node.js version
        run: |
          node -v
          cat /etc/os-release
